apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pepr-informer
  name: pepr-informer
  namespace: pepr-informer
spec:
  template:
    spec:
      containers:
      - image: pepr-informer:prod
        name: pepr-informer 
